# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v28VH5N7cAp9Kl8gkJj6S2EXpwntXyl5
"""

import streamlit as st
import agent_logic

st.set_page_config(page_title="자취생 밥선생", page_icon="🍳")

st.title("🍳 자취생을 위한 엄마 밥선생")
st.caption("엄마! 냉장고에 있는 걸로 뭐 해먹을까?")

# 3. 세션 상태 초기화
# 사용자가 새로고침하기 전까지 대화 내용 저장 및 기억

if "messages" not in st.session_state:
    st.session_state.messages = []
    # 첫 인사말 추가
    st.session_state.messages.append({"role": "assistant", "content": "우리 딸/아들 왔어? 밥은 챙겨 먹었니? 뭐 해줄까?"})

# DB와 LLM 로드
if "agent_loaded" not in st.session_state:
    try:
        db, llm = agent_logic.get_agent_components()
        st.session_state.db = db
        st.session_state.llm = llm
        st.session_state.agent_loaded = True
    except Exception as e:
        st.error(f"오류가 발생했습니다: {e}")
        st.stop()

# 채팅 화면 구현

for msg in st.session_state.messages:
    if msg["role"] == "user":
        st.chat_message("user").write(msg["content"])
    else:
        st.chat_message("assistant").write(msg["content"])

# 사용자 입력 처리

if prompt := st.chat_input("질문을 입력하세요... (예: 계란으로 뭐 해먹을까?)"):

    # 1. 사용자 메시지 화면에 표시 및 저장
    st.chat_message("user").write(prompt)
    st.session_state.messages.append({"role": "user", "content": prompt})

    # 2. 에이전트에게 답변 요청 (Multi-turn을 위해 기록 전달)
    # 현재까지의 대화 기록을 (User, AI) 튜플 형태로 변환
    chat_history = []
    for msg in st.session_state.messages[:-1]:
        role = "자식" if msg["role"] == "user" else "엄마"
        chat_history.append((role, msg["content"]))

    with st.spinner("엄마가 레시피 노트 찾는 중..."):
        # agent_logic 함수 호출
        response_text, retrieved_doc = agent_logic.generate_response(
            st.session_state.db,
            st.session_state.llm,
            prompt,
            chat_history
        )

    # 3. AI 답변 화면에 표시 및 저장
    st.chat_message("assistant").write(response_text)
    st.session_state.messages.append({"role": "assistant", "content": response_text})

    # RAG가 어떤 문서를 찾았는지 궁금하면 아래 주석 해제
    with st.expander("엄마가 참고한 레시피 노트 보기"):
        st.info(retrieved_doc)